### ISSUE TITLE
bundle failed to load command: bin/trello-download

### ISSUE THREAD

**Issue by patrickwelker** [fiedl/trello-downloader#1]
Hi Sebastian,

any ideas how to troubleshoot this? ⬇️⬇️⬇️ 

Running `trello-download` with the `--help` option works:

    $ bundle exec bin/trello-download --help
    Usage: trello-download [options] url
           --download-directory=PATH    Defauts to ~/Downloads

But when trying to get an actual board or card like "https://trello.com/c/AyjfuWc2/32-check-out-our-trello-team-playbooks-click-for-info" it fails saying it can't find the command:

    $ bundle exec bin/trello-download "https://trello.com/c/AyjfuWc2/32-check-out-our-trello-team-playbooks-click-for-info"

    Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/meme/Downloads/Interview Pipeline/2018-03-27 Check out our Trello Team playbooks (click for info)/card.json
    bundler: failed to load command: bin/trello-download (bin/trello-download)
      /Users/meme/Scripts/Third-Party/trello-downloader/lib/trello_downloader.rb:43:in `initialize'
      /Users/meme/Scripts/Third-Party/trello-downloader/lib/trello_downloader.rb:43:in `open'
      /Users/meme/Scripts/Third-Party/trello-downloader/lib/trello_downloader.rb:43:in `export_to_json_and_yaml'
      /Users/meme/Scripts/Third-Party/trello-downloader/lib/trello_downloader.rb:38:in `export'
      /Users/meme/Scripts/Third-Party/trello-downloader/lib/trello_downloader.rb:12:in `download_card'
      bin/trello-download:36:in `block in <top (required)>'
      bin/trello-download:34:in `each'
      bin/trello-download:34:in `<top (required)>'

Installed gems:

    $ bundle show
    Gems included by the bundle:
      * activemodel (5.1.5)
      * activesupport (5.1.5)
      * addressable (2.5.2)
      * bundler (1.16.1)
      * coderay (1.1.2)
      * colored (1.2)
      * concurrent-ruby (1.0.5)
      * domain_name (0.5.20170404)
      * fiedl-log (0.3.0)
      * http-cookie (1.0.3)
      * i18n (0.9.5)
      * json (2.1.0)
      * method_source (0.9.0)
      * mime-types (3.1)
      * mime-types-data (3.2016.0521)
      * minitest (5.11.3)
      * netrc (0.11.0)
      * oauth (0.5.4)
      * pry (0.11.3)
      * public_suffix (3.0.2)
      * rest-client (2.0.2)
      * ruby-trello (2.0.1)
      * thread_safe (0.3.6)
      * tzinfo (1.2.5)
      * unf (0.1.4)
      * unf_ext (0.0.7.5)

Here's my Gemfile.lock:

    GEM
      remote: https://rubygems.org/
      specs:
        activemodel (5.1.5)
          activesupport (= 5.1.5)
        activesupport (5.1.5)
          concurrent-ruby (~> 1.0, >= 1.0.2)
          i18n (~> 0.7)
          minitest (~> 5.1)
          tzinfo (~> 1.1)
        addressable (2.5.2)
          public_suffix (>= 2.0.2, < 4.0)
        coderay (1.1.2)
        colored (1.2)
        concurrent-ruby (1.0.5)
        domain_name (0.5.20170404)
          unf (>= 0.0.5, < 1.0.0)
        fiedl-log (0.3.0)
          colored
        http-cookie (1.0.3)
          domain_name (~> 0.5)
        i18n (0.9.5)
          concurrent-ruby (~> 1.0)
        json (2.1.0)
        method_source (0.9.0)
        mime-types (3.1)
          mime-types-data (~> 3.2015)
        mime-types-data (3.2016.0521)
        minitest (5.11.3)
        netrc (0.11.0)
        oauth (0.5.4)
        pry (0.11.3)
          coderay (~> 1.1.0)
          method_source (~> 0.9.0)
        public_suffix (3.0.2)
        rest-client (2.0.2)
          http-cookie (>= 1.0.2, < 2.0)
          mime-types (>= 1.16, < 4.0)
          netrc (~> 0.8)
        ruby-trello (2.0.1)
          activemodel (>= 3.2.0)
          addressable (~> 2.3)
          json
          oauth (>= 0.4.5)
          rest-client (>= 1.8.0)
        thread_safe (0.3.6)
        tzinfo (1.2.5)
          thread_safe (~> 0.1)
        unf (0.1.4)
          unf_ext
        unf_ext (0.0.7.5)

    PLATFORMS
      ruby

    DEPENDENCIES
      fiedl-log!
      json!
      pry!
      ruby-trello!

    BUNDLED WITH
      1.16.1

Installing `trello-downloader` globally might work, but I'm all for not cluttering my gem list if possible (and using `rbenv` instead – works great on [weavenet/trello_cli Ruby Gem](https://github.com/weavenet/trello_cli)).

**Comment by fiedl** [comment]
Thanks for your bug report.

The issue isn't with loading via bundler. In fact, the export does fail because, for some reason, the parent directory hasn't been created, yet.

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/meme/Downloads/Interview Pipeline/2018-03-27 Check out our Trello Team playbooks (click for info)/card.json
```

I should be able to fix this in a minute.

**Comment by fiedl** [comment]
Please update and try again.

```bash
cd trello-downloader
git pull origin master

bundle exec bin/trello-download "https://trello.com/c/AyjfuWc2/32-check-out-our-trello-team-playbooks-click-for-info"
```

**Comment by patrickwelker** [comment]
I wasn't sure if it was a mkdir issue because I manually tried to create the dirs and it still failed. Glad it was an easy fix.

Although `trello-downloader` works with the URL provided now, but I'm still not getting constant results. I'll post them in a separate issue to keep things neat and clean here.
