### ISSUE TITLE
Feature suggestion: expand short urls

### ISSUE THREAD

**Issue by patrickwelker** [fiedl/trello-downloader#3]
The default Trello sharing dialog allows to copy shortened URL's like `https://trello.com/c/AyjfuWc2`. It would be useful if those could be auto-expanded to the full URL `https://trello.com/c/AyjfuWc2/32-check-out-our-trello-team-playbooks-click-for-info`.

**Comment by fiedl** [comment]
Thanks for the suggestion. This has been a simple fix, modifying the card id regex (https://github.com/fiedl/trello-downloader/commit/67a6d5325d998f988246449607e456bc413e34e9).
